version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOW_ALL_ORIGINS=True
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api